version: '3.7'
services:
  py:
    build:
      context: .
      dockerfile: ./python-docker/Dockerfile
    container_name: py
    volumes:
      - ./app/python/base:/app
    restart: always
    tty: true

  es:
    build: ./elasticsearch-docker
    container_name: es
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./app/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./app/elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    ports:
      - 9200:9200

  kibana:
    build: ./kibana-docker
    container_name: kibana
    links:
      - es:elasticsearch
    ports:
      - 5601:5601

volumes:
  esdata:
    driver: local
